# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-15 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=200)),
                ('Primer_Apellido', models.CharField(max_length=200)),
                ('Segundo_Apellido', models.CharField(max_length=200)),
                ('Telefono', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=200)),
                ('Domicilio', models.CharField(max_length=200)),
                ('Fecha_Nacimiento', models.DateField()),
                ('Antecedentes_Personales', models.TextField()),
                ('Antecedentes_Familiares', models.TextField()),
                ('Historia_Clinica', models.TextField(verbose_name='Historia Clinica')),
                ('Dia_registro', models.DateTimeField(verbose_name='Fecha')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=200)),
                ('Telefono', models.CharField(max_length=200)),
                ('Mensaje', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=200)),
                ('Contenido', models.TextField()),
                ('Fecha_Creacion', models.DateTimeField(verbose_name='Fecha de creacion')),
                ('Publico_Privado', models.CharField(choices=[('pub', 'publico'), ('pri', 'privado')], default='pub', max_length=3)),
                ('Foto', models.ImageField(default='SOMETHING', upload_to='postPhotos')),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Diagnostico', models.TextField()),
                ('Tratamiento', models.TextField()),
                ('Observaciones', models.TextField()),
                ('Dia', models.DateField(verbose_name='Dia de la visita')),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Cliente')),
            ],
        ),
    ]
