# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-13 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20161013_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='Hist',
            field=models.CharField(default=0, max_length=600),
            preserve_default=False,
        ),
    ]
