# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-13 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_clientes_hist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=200)),
                ('Cliente', models.CharField(max_length=200)),
                ('Observaciones', models.CharField(max_length=600)),
                ('Dia', models.DateTimeField(verbose_name='date')),
            ],
        ),
    ]
