# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-13 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_citas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=200)),
                ('Cliente', models.CharField(max_length=200)),
                ('Observaciones', models.CharField(max_length=600)),
                ('Dia', models.DateTimeField(verbose_name='date')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=200)),
                ('DNI', models.CharField(max_length=200)),
                ('Hist', models.CharField(max_length=600)),
                ('Dia_registro', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.DeleteModel(
            name='Citas',
        ),
        migrations.DeleteModel(
            name='Clientes',
        ),
    ]
