# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-13 17:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20161013_1904'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cita',
            new_name='Citas',
        ),
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Clientes',
        ),
    ]
