# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-14 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20161014_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='dateOfCreation',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='creation_date',
            field=models.DateTimeField(verbose_name='date'),
        ),
    ]
