# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-14 15:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20161014_1301'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='BlogCategoria',
        ),
        migrations.RenameModel(
            old_name='Post',
            new_name='BlogPost',
        ),
    ]
