# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-27 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_holaquetal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holaquetal',
            name='category',
        ),
        migrations.DeleteModel(
            name='holaquetal',
        ),
    ]
