# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-04 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20161027_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Publico_Privado',
            field=models.CharField(choices=[('pub', 'publico'), ('pri', 'privado')], default='pub', max_length=3),
        ),
    ]
