# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-04 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_post_publico_privado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='Categoria',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='Contenido',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='creation_date',
            new_name='Fecha_Creacion',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='Titulo',
        ),
    ]
