# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-04 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20161104_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Foto',
            field=models.ImageField(default='SOMETHING', upload_to='postPhotos'),
        ),
    ]
