# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-09 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_post_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='Nombre',
        ),
        migrations.AddField(
            model_name='cita',
            name='Apellido1',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cita',
            name='Apellido2',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cita',
            name='Diagnostico',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cita',
            name='Tratamiento',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
    ]
