# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-12 17:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_auto_20161111_1604'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cita',
            new_name='Visita',
        ),
    ]
